server:
  host: 127.0.0.1
  port: 443

spring:
  profiles:
    active: secret


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /home/**
      - /product/**
      - /brand/**
      - /sso/**
      - /files/**


cim:
  app:
    port: 23456
  websocket:
    port: 34567



apple:
  apns:
    debug: false
    p12:
      password: 123
      file: xxx
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
