spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

qiniu:
  accessKey:
  secretKey:

server:
  ssl:
    key-store-type: PKCS12
    key-store-password:
    key-store:
      classpath: